name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Display structure of files 12
      run: ls -laR
    - uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci.yml
        name: test-results
    - name: Display structure of files 2
      run: ls -laR
    - name: Test Report
      uses: phoenix-actions/test-reporting@v11
      id: test-report
      with:
        name: Mocha Tests
        path: test-results.json
        reporter: mocha-json
    - name: c8 coverage report
      uses: romeovs/lcov-reporter-action@v0.2.16