name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ci.yml
        name: test-results
    - name: Test Report
      uses: phoenix-actions/test-reporting@v11
      id: test-report
      with:
        name: Mocha Tests
        path: test-results.json
        reporter: mocha-json